version: '3.5'
services:

  web:
    build: docker/web
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/super-potato:consistent

  db:
    build: docker/mysql
    ports:
      - 8306:3306
    environment:
      MYSQL_DATABASE: super-potato
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
